# Generated by Django 4.2.4 on 2023-08-23 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_inventory_alter_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
    ]
