# Generated by Django 4.2.4 on 2023-09-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='test',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
