# Generated by Django 4.2.4 on 2023-09-05 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_test_alter_product_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='test',
        ),
    ]
