# Generated by Django 4.2.4 on 2023-09-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='f',
            field=models.BooleanField(default=False),
        ),
    ]
