# Generated by Django 4.2.4 on 2023-09-05 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_product_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='f',
            new_name='feature',
        ),
    ]
